import React, { useState } from 'react';
import { Card } from '../../components/ui/Card';
import { Report, View } from '../../types';
import { ArrowLeft, Plus, Download } from 'lucide-react';

interface FinancialReportsProps {
  navigate: (view: View) => void;
}

const mockReports: Report[] = [
    { id: 'FR-001', name: 'Q4 2025 Revenue Summary', generatedBy: 'Admin', date: '2025-11-01', format: 'PDF' },
    { id: 'FR-002', name: 'October 2025 Detailed Transaction Log', generatedBy: 'J. Smith', date: '2025-11-01', format: 'CSV' },
    { id: 'FR-003', name: 'Q3 2025 Revenue Summary', generatedBy: 'Admin', date: '2025-10-01', format: 'PDF' },
];


const FinancialReports: React.FC<FinancialReportsProps> = ({ navigate }) => {
  return (
    <div className="space-y-6">
      <div className="flex items-center space-x-3">
        <button onClick={() => navigate('operational-reports')} className="p-2 rounded-full hover:bg-brand-gray-100">
            <ArrowLeft className="w-5 h-5 text-brand-gray-600" />
        </button>
        <div>
          <h1 className="text-2xl font-bold">Financial Reports</h1>
          <p className="text-brand-gray-600">Generate reports on revenue, refunds, and arrears.</p>
        </div>
      </div>
      
        <Card>
            <h2 className="text-lg font-semibold mb-4">Generate New Report</h2>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
                <div className="md:col-span-2">
                    <label className="text-sm font-medium">Report Type</label>
                    <select className="mt-1 w-full border p-2 rounded bg-white">
                        <option>Revenue Summary by Department</option>
                        <option>Detailed Transaction Log</option>
                        <option>Outstanding Fees Report</option>
                    </select>
                </div>
                 <div>
                    <label className="text-sm font-medium">Date Range</label>
                    <input type="date" className="mt-1 w-full border p-2 rounded"/>
                </div>
                 <div>
                    <button className="w-full bg-brand-blue-600 text-white font-semibold py-2 rounded-lg flex items-center justify-center"><Plus size={16} className="mr-2"/> Generate</button>
                </div>
            </div>
        </Card>

      <Card>
        <h2 className="text-lg font-semibold mb-4">Previously Generated Reports</h2>
        <div className="overflow-x-auto">
            <table className="w-full text-sm text-left">
                <thead className="text-xs text-brand-gray-500 uppercase bg-brand-gray-50">
                    <tr>
                        <th className="px-4 py-3">Report Name</th>
                        <th className="px-4 py-3">Generated By</th>
                        <th className="px-4 py-3">Date</th>
                        <th className="px-4 py-3 text-right">Download</th>
                    </tr>
                </thead>
                <tbody>
                    {mockReports.map(report => (
                        <tr key={report.id} className="border-b">
                            <td className="px-4 py-3 font-medium">{report.name}</td>
                            <td className="px-4 py-3">{report.generatedBy}</td>
                            <td className="px-4 py-3">{report.date}</td>
                            <td className="px-4 py-3 text-right">
                                <button className="font-medium text-brand-blue-600 hover:underline flex items-center ml-auto">
                                    <Download size={14} className="mr-1.5"/> {report.format}
                                </button>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
      </Card>
    </div>
  );
};

export default FinancialReports;